# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 992d62e0dc5677086ac54dc4353d0b690ecc6b09e714085b6f30aa53f35f0b6dfe6c46dfbc5fef0e72b3d166e20bb04711694cbbee3188f7ace96ea0893c7075

test:
  secret_key_base: a72465e7575a3d00d3df58f977977d61525c18fca7d9925eb4d02a69be2ffd1190a3b488c6962a8eba4aaa2b50138544a5e948e21b5108b42d42a89583a87468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
